import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Navbar";
import {
  Text,
  Spacer,
  Input,
  Switch,
  Radio,
  Checkbox,
  Textarea,
  Grid,
  Container,
  Progress,
  Image,
} from "@nextui-org/react";
import { Box } from "../components/Box";
import { Layout } from "../components/Layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Certificados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Box css={{ px: "$12", mt: "$8", "@xsMax": { px: "$10" } }}>
          <Image src="/certificate_ignite.jpg" alt="Default Image" />
          <Spacer y={1} />

          <Image src="/certificate_discover.jpg" alt="Default Image" />

          <Spacer y={1} />
          <Image src="certificado_js_web.jpg" alt="Default Image" />
          <Spacer y={1} />
          <Image src="certificado_redux.jpg" alt="Default Image" />
        </Box>
      </main>
    </Layout>
  );
};

export default Home;
